Barfi/Models/Bar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Barfi.Models
{
    public class Bar
    {
        public int ID { get; set; }
        [Required, Display(Name = "Name"), MaxLength(255)]
        public string name { get; set; }
        [Required]
        public bool WIFI { get; set; }
        [Required, Range(1,5)]
        public int starRating { get; set; }
        [Required, Range(-180,180)]
        public double latitude { get; set; }
        [Required, Range(-180,180), ]
        public double longitude { get; set; }
        


    }
}

Barfi/Models/GreetingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Barfi.Models
{
    public class GreetingViewModel
    {
        public IEnumerable<Bar> Bars { get; set; }
        public string Message { get; set; }

    }
}

Barfi/Controllers/BarfiController.cs
using Barfi.Models;
using Barfi.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Barfi.Controllers
{
    public class BarfiController : Controller
    {
        private readonly IBarData db;
        public BarfiController(IBarData db)
        {
            this.db = db;
        }
        [HttpGet]
        public ActionResult Index()
        {
            var model = db.getAll();
            return View(model);
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            var model = db.Get(id);
            if(model == null)
            {
                return View("NotFound");
            }
            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = db.Get(id);
            if(model == null)
            {
                return View("NotFound");
            }
            return View(model);
        }

        [HttpGet]
         public ActionResult Delete(int id)
        {
            var model = db.Get(id);
            if (model == null)
            {
                return View("NotFound");
            }
            return View(model); ;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Bar bar)
        {
            if(ModelState.IsValid)
            {
                db.Update(bar);
                return RedirectToAction("Details", new { id = bar.ID });
            }
            return View(bar);
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Bar bar)
        {
            if(ModelState.IsValid)
            {
                db.Add(bar);
                return RedirectToAction("Details", new { id = bar.ID });
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FormCollection form)
        {
            db.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Barfi/Controllers/GreetingController.cs
using Barfi.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Barfi.Controllers
{
    public class GreetingController : Controller
    {
        // GET: Greeting
        public ActionResult Index()
        {
            var model = new GreetingViewModel();
            model.Message = ConfigurationManager.AppSettings["message"];
            return View(model);
        }
    }
}

Barfi/Controllers/HomeController.cs
using Barfi.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Barfi.Controllers
{
    public class HomeController : Controller
    {
        IBarData db;
        //Add IOC container.
        public HomeController(IBarData db)
        {
            this.db = db;
        }
        public ActionResult Index()
        {
            var model = db.getAll();
            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "BarFi description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Barfi contact page.";

            return View();
        }

        public ActionResult Meeseeks()
        {
            ViewBag.Message = "Hi I'm Mr. Meeseeks!";

            return View();
        }
    }
}

Barfi/Views/Barfi/Create.cshtml
@model Barfi.Models.Bar

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Bar</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.WIFI, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.WIFI)
                @Html.ValidationMessageFor(model => model.WIFI, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.starRating, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.starRating, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.starRating, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.latitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.latitude, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.latitude, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.longitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.longitude, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.longitude, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Barfi/Views/Barfi/Delete.cshtml
@model Barfi.Models.Bar

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bar</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WIFI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WIFI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.starRating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.starRating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.latitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.longitude)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Barfi/Views/Barfi/Details.cshtml
@model Barfi.Models.Bar

@{
    ViewBag.Title = "Details";
}

<h2>Details for @Html.DisplayFor(model => model.name)</h2>

<div>
    <h4>Bar</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WIFI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WIFI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.starRating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.starRating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.latitude)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.longitude)
        </dd>




    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Barfi/Views/Barfi/Edit.cshtml
@model Barfi.Models.Bar

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WIFI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.WIFI)
                    @Html.ValidationMessageFor(model => model.WIFI, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.starRating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.starRating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.starRating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Barfi/Views/Barfi/Index.cshtml
@model IEnumerable<Barfi.Models.Bar>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WIFI)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.starRating)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.latitude)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.longitude)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.WIFI)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.starRating)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.latitude)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.longitude)
    </td>

    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
    </td>
</tr>
}

</table>

Barfi/Views/Barfi/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}

<h2>Sorry that bar was not found.</h2>
@Html.ActionLink("Back to List", "Index")

Barfi/Views/Greeting/index.cshtml
@model Barfi.Models.GreetingViewModel
@{
    ViewBag.Title = "index";
}

<h2>index</h2>
@Model.Message

Barfi/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>BarFi is currently under construction.</p>

Barfi/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Check us out on <a href="https://github.com/irichard03/BarFi">Github</a></p>

Barfi/Views/Home/Index.cshtml
@model IEnumerable<Barfi.Models.Bar>

@{
    ViewBag.Title = "BarFi";
}

<div class="jumbotron">
    <h1>BarFi.info</h1>
    <p class="lead">Coming Soon</p>
    <p>Lookup local bars with WiFi in your area so you can achieve Balmer Peak performance.</p>
</div>

<div class="row">
    <div class="col-md-4">
        There are @Model.Count() Bars in the dataset.
    </div>
</div>



<div class="row">
    <div class="col-md-4">
        <h2>Planned Features</h2>
        <p>
            Integrate with Google API to find nearby bars
        </p>
    </div>
    <div class="col-md-4">
        <h2>Crowdsource Intel!</h2>
        <p>Help improve BarFi, do your part and add bars with good WiFi.</p>
    </div>
</div>

Barfi/Views/Home/Meeseeks.cshtml
@{
    ViewBag.Title = "Meeseeks";
}

<h2>@ViewBag.Title.</h2>
<h3>Hey, I'm Mr. Meeseeks, look at me!</h3>

Barfi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BarFi", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Bars", "Index", "Barfi")</li>
                    <li>@Html.ActionLink("Meeseeks", "Meeseeks", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ian Richard</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>